apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fluent-bit.fullname" . }}-elassandra-pipeline
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "fluent-bit.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  fluentbit-pipeline.json: |-
    {
       "description" : "fluentbit elassandra pipeline",
       "processors" : [
         {
           "timeuuid" : {
             "field": "es_time",
             "target_field": "ts",
             "formats" : ["ISO8601"],
             "timezone" : "Europe/Amsterdam"
           }
         },
         {
           "set" : {
             "field": "_id",
              "value": "[\"{{ "{{" }}kubernetes.docker_id{{ "}}" }}\",\"{{ "{{" }}ts{{ "}}" }}\"]"
           }
         }
       ]
    }